%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Estimulema git\Estimulema\Estimulema Diag and Train\Treinamento.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/08 20:57:02

%% Initialize variables.
filename = 'C:\Estimulema git\Estimulema\Estimulema Diag and Train\Treinamento0.txt';
delimiter = ';';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Treinamento = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','VarName2','VarName3','VarName4','VarName5'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%% graficar variables

x = Treinamento.VarName2;
y = Treinamento.VarName3;
z = Treinamento.VarName4;
stim = Treinamento.VarName5;

figure();
plot(x)
hold on
plot(y)
plot(z)

figure();
plot(stim)